
/*****************************************************************************
*
* File:  $MRD_HOME/etc/sql/mrd_indexes.sql
* Author:  
*
* Remarks:  This script is used to create the indexes on the MRD
*
* Version Information
*
* Release:21
* Version: 0.1
* Authority: BAC 
* Date: 04/22/2005
*
*   04/22/2005 2.0.1 (BAC): Release 2 started
*   04/14/2005 1.3.4 (BAC): mrd_stringtab uses hashcode, double-check
*			  of mrd_* and tmp_* table indexes
*   05/25/2004 3.3 (BAC): +mrd_cui_history, mrd_content_view_members
*   04/29/2004 3.2 (BAC): Use tablespace MRDI
*   03/12/2003 3.1 (BAC): AUI index on classes
*   12/7/2001 3.0 (BAC):  This version of the script was used for
* 			  the load used to produce 2002AA.
*   6/4/2001  2.1 (BAC):  Made mrd_source_rank, mrd_termgroup_rank primary
*                         keys into regular indexes.
*   5/4/2001  2.0 (BAC):  Cleaned up the file, put all indexes in
* 			  tablespace MIDI.
*
*   4/16/2001 1.90 (BAC): Replaced indexes on MID tables with
*             a call to @@$MEME_HOME/etc/sql/meme_indexes.sql
*	
*   
*   See old/ indexes.sql for older comments
* 
*****************************************************************************/


/*****************  MID Indexes ******************/
-- No longer do this:
-- @@$MEME_HOME/etc/sql/meme_indexes.sql


/*****************  MRD Indexes - MID tables ************/

-- indexed in MID now
--CREATE INDEX x_classes_last_release_cui ON classes(last_release_cui)
--PCTFREE 10 STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_classes_aui ON classes(aui)
PCTFREE 10 STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_classes_last_assigned_cui ON classes(last_assigned_cui)
PCTFREE 10 STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;


/*****************  MRD Indexes - MRD aux. tables *******/ 

ALTER INDEX ae_pk REBUILD STORAGE (INITIAL 20M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

ALTER INDEX clc_pk REBUILD STORAGE (INITIAL 20M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

ALTER INDEX tmp_classes_pk REBUILD STORAGE (INITIAL 20M) 
TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

ALTER INDEX tmp_concepts_pk REBUILD STORAGE (INITIAL 20M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

--ALTER INDEX tmp_attributes_pk REBUILD STORAGE (INITIAL 20M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

--ALTER INDEX tmp_relationships_pk REBUILD STORAGE (INITIAL 20M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_con_cn1 ON connected_concepts (concept_id_1,concept_id_2)
PCTFREE 10 STORAGE (INITIAL 10M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_con_cn2 ON connected_concepts (concept_id_2,concept_id_1)
PCTFREE 10 STORAGE (INITIAL 10M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

ALTER INDEX conc_pk REBUILD STORAGE (INITIAL 20M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_css_sid ON connected_sets(set_id)
PCTFREE 10 STORAGE (INITIAL 20M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_css_cid ON connected_sets(concept_id)
PCTFREE 10 STORAGE (INITIAL 20M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_cs_cid ON connected_set (cui)
PCTFREE 10 STORAGE (INITIAL 20M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

ALTER INDEX dtd_pk REBUILD TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_eh_lmidid ON extraction_history (last_mid_event_id)
PCTFREE 10 STORAGE (INITIAL 10M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

ALTER INDEX eq_pk REBUILD STORAGE (INITIAL 20M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

ALTER INDEX ep_pk REBUILD STORAGE (INITIAL 200M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_ep_aid ON events_processed (action_id)
PCTFREE 10 STORAGE (INITIAL 200M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

ALTER INDEX fq_pk REBUILD STORAGE (INITIAL 20M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_fq_mid ON feedback_queue(mid_event_id)
PCTFREE 10 STORAGE (INITIAL 20M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

ALTER INDEX rh_pk REBUILD TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;


/*****************  MRD Indexes - MRD core tables *******/ 

CREATE INDEX x_ma_d ON mrd_attributes (insertion_date, expiration_date)
PCTFREE 10 STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE BITMAP INDEX x_ma_atn ON mrd_attributes (attribute_name)
PCTFREE 10 STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_ma_cui ON mrd_attributes (cui) PCTFREE 10 
STORAGE (INITIAL 130M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_ma_id ON mrd_attributes (atui) PCTFREE 10 
STORAGE (INITIAL 80M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mc_d ON mrd_classes (insertion_date, expiration_date)
PCTFREE 10 STORAGE (INITIAL 10M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mc_sui ON mrd_classes (sui) PCTFREE 10 
STORAGE (INITIAL 10M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mc_cui ON mrd_classes (cui,aui) PCTFREE 10 
STORAGE (INITIAL 80M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mc_id ON mrd_classes (aui,cui) PCTFREE 10 
STORAGE (INITIAL 80M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mc_tty ON mrd_classes (tty) PCTFREE 10 
STORAGE (INITIAL 80M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mcoch_cid ON mrd_coc_headings (citation_set_id) PCTFREE 10 
STORAGE (INITIAL 200M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mcoch_haui ON mrd_coc_headings (heading_aui) PCTFREE 10 
STORAGE (INITIAL 200M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mcocsh_ssid ON mrd_coc_subheadings (citation_set_id) PCTFREE 10 
STORAGE (INITIAL 200M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mcs_d ON mrd_concepts (insertion_date, expiration_date)
PCTFREE 10 STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mcs_cui ON mrd_concepts (cui) PCTFREE 10 
STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mcs_id ON mrd_concepts (concept_id) PCTFREE 10 
STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mcxt_aid ON mrd_contexts (aui) PCTFREE 10 
STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mcxt_ptn ON mrd_contexts (parent_treenum) PCTFREE 10 
STORAGE (INITIAL 500M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mcvm_mui ON mrd_content_view_members (meta_ui) PCTFREE 10 
STORAGE (INITIAL 50M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mcui_cui1 ON mrd_cui_history (cui1) PCTFREE 10 
STORAGE (INITIAL 50M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

--CREATE INDEX x_mns_aid ON mrd_normstr (normstr_id) PCTFREE 10 
--STORAGE (INITIAL 150M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

--CREATE INDEX x_mnw_aid ON mrd_normwrd (normwrd_id) PCTFREE 10 
--STORAGE (INITIAL 150M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

--CREATE INDEX x_mw_aid ON mrd_word_index (aui) PCTFREE 10 
--STORAGE (INITIAL 150M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mr_d ON mrd_relationships (insertion_date,expiration_date)
PCTFREE 10 STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mr_cui_1 ON mrd_relationships (cui_1) PCTFREE 10 
STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mr_cui_2 ON mrd_relationships (cui_2) PCTFREE 10 
STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mr_atid_1 ON mrd_relationships (aui_1) PCTFREE 10 
STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mr_atid_2 ON mrd_relationships (aui_2) PCTFREE 10 
STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mr_id ON mrd_relationships (rui) PCTFREE 10 
STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mr_ra ON mrd_relationships (RELATIONSHIP_ATTRIBUTE) PCTFREE 10 
STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mr_rn ON mrd_relationships (RELATIONSHIP_NAME) PCTFREE 10 
STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mstab_sid ON mrd_stringtab (hashcode) PCTFREE 10 
STORAGE (INITIAL 100M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mrd_source_rank ON mrd_source_rank (source) PCTFREE 10
STORAGE (INITIAL 10M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_mrd_tg_rank ON mrd_termgroup_rank (termgroup) PCTFREE 10
STORAGE (INITIAL 10M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

/*****************  MRD Indexes - MRD tmp core tables *******/ 

CREATE INDEX x_tc_aui on tmp_classes (aui) PCTFREE 10
STORAGE (INITIAL 60M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_tc_cid on tmp_classes (cui) PCTFREE 10
STORAGE (INITIAL 60M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_tr_rui ON tmp_relationships (rui) PCTFREE 10 
STORAGE (INITIAL 30M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_tr_coid_1 ON tmp_relationships (cui_1) PCTFREE 10 
STORAGE (INITIAL 30M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_tr_coid_2 ON tmp_relationships (cui_2) PCTFREE 10 
STORAGE (INITIAL 30M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_tr_atid_1 ON tmp_relationships (aui_1) PCTFREE 10 
STORAGE (INITIAL 30M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_tr_atid_2 ON tmp_relationships (aui_2) PCTFREE 10 
STORAGE (INITIAL 30M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_ta_atuid ON tmp_attributes (atui) PCTFREE 10 
STORAGE (INITIAL 50M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_ta_uid ON tmp_attributes (ui) PCTFREE 10 
STORAGE (INITIAL 50M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_ta_cid ON tmp_attributes (cui) PCTFREE 10 
STORAGE (INITIAL 50M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;

CREATE INDEX x_ts_id ON tmp_concepts (concept_id) PCTFREE 10 
STORAGE (INITIAL 20M) TABLESPACE MRDI COMPUTE STATISTICS PARALLEL;


/**************** Prepare meme_indexes, meme_ind_columns ******/

DELETE FROM meme_indexes;
INSERT INTO meme_indexes 
SELECT index_name, table_name, pct_free, pct_increase, initial_extent,
next_extent, min_extents, max_extents, tablespace_name, index_type, uniqueness
FROM user_indexes;

DELETE FROM meme_ind_columns;
INSERT INTO meme_ind_columns SELECT * FROM user_ind_columns;
