#!/bin/csh -f

if ($?ENV_HOME != 1) then
   setenv ENV_HOME /usr/d5/ENV
endif
setenv ENV_FILE $ENV_HOME/etc/env.prop
source $ENV_HOME/bin/env.csh
echo $INV_HOME/bin

set os = `uname`;

if ("$os" == "SunOS") then
	$INV_HOME/bin/echarcount_solaris $*
else if ("$os" == "Linux") then
	$INV_HOME/bin/echarcount_linux $*
else
	echo "Sorry, echarcount has not been compiled for $os"
	exit 1
endif
