#!/bin/csh -f
# Script: maxfield awkfield filename
# Outputs the maxlength of the awkfield in filename
# maxfield '$2' junk -- displays maximum length of the 2nd "|"-delimited field
#			  in file junk
# maxfield '$0' junk -- displays maximum line length in file junk

if ($#argv != 2) then
	echo "Usage: $0 'awkfield' filename"
	exit 1
endif

awk -F\| '(length('$1')>maxlen) {maxlen=length('$1')} END { print maxlen }' $2
