/*****************************************************************************
 *
 * Package:    com.lexical.meme.core
 * Object:     AdHocQueryFactFilter.java
 * 
 * Author:     Brian Carlsen
 *
 *****************************************************************************/
package gov.nih.nlm.recipe;

import java.io.Serializable;


/**
 * This class contains all of the information to describe
 * a filter for facts generated by matching or some other process;
 *
 * @author Brian A. Carlsen
 * @version 1.0
 *
 */
public class AdHocQueryFactFilter extends FactFilter implements Serializable {

  //
  // These fields are public to facilitate ease of use
  //
  public String query = "";

  /**
   * Constructor
   */
  public AdHocQueryFactFilter () { 
  };

  /**
   * Constructor
   */
  public AdHocQueryFactFilter ( String sql ) {
    type_1 = "AD_HOC_QUERY";
    query = sql;
  };

  /**
   * Overrides toString()
   * @return string
   */
  public String toString() {
    return type_1 + ": See Script For Details";
  }

  /**
   * Long description
   * @return String
   */
  public String longDescription () {
    return toString();
  }

  /**
   * Overrides equals
   * @return boolean 
   */
  public boolean equals (Object obj) {
    System.out.println("AdHocQueryFactFilter::equals("+obj+")");

    if (! (obj instanceof AdHocQueryFactFilter))
      return false;
    
    return longDescription().equals( ((AdHocQueryFactFilter)obj).longDescription());
  }


  /**
   * Write shell script code for this filter.
   */
  public String toShellScript (String merge_set) {
    return "    -- AD HOC SQL Filter\n" + query + "\n";
  }
}
