/*****************************************************************************
 *
 * Package:    com.lexical.meme.core
 * Object:     AdHocFactFilter.java
 * 
 * Author:     Brian Carlsen
 *
 *****************************************************************************/
package gov.nih.nlm.recipe;

import java.io.Serializable;


/**
 * This class contains all of the information to describe
 * a filter for facts generated by matching or some other process;
 *
 * @author Brian A. Carlsen
 * @version 1.0
 *
 */
public class AdHocFactFilter extends FactFilter implements Serializable {

  //
  // These fields are public to facilitate ease of use
  //
  public String script = "";

  /**
   * Constructor
   */
  public AdHocFactFilter () { 
  };

  /**
   * Constructor
   */
  public AdHocFactFilter ( String script ) {
    type_1 = "AD_HOC";
    this.script = script;
  };

  /**
   * Overrides toString()
   * @return string
   */
  public String toString() {
    StringBuffer sb = new StringBuffer();
    sb.append(type_1);
    sb.append(" : " + script);
    return sb.toString();
  }

  /**
   * Long description
   * @return String
   */
  public String longDescription () {
    return toString();
  }

  /**
   * Overrides equals
   * @return boolean 
   */
  public boolean equals (Object obj) {
    System.out.println("AdHocFactFilter::equals("+obj+")");

    if (! (obj instanceof AdHocFactFilter))
      return false;
    
    return longDescription().equals( ((AdHocFactFilter)obj).longDescription());
  }


  /**
   * Write shell script code for this filter.
   */
  public String toShellScript (String merge_set) {
    return "    -- " + toString() + "\n    !" + script + "\n";
  }
}
